# Copyright (c) 2024 Aqeel AlShafei
#
# This software is licensed under the MIT License.
# You may obtain a copy of the License at:
# https://opensource.org/licenses/MIT

[env]
term = "xterm-256color"

[font]
size = 11.5
builtin_box_drawing = true

normal = { family = "JetBrains Mono NL", style = "Retina"}
bold = { family = "JetBrains Mono ExtraBold", style = "Bold"}
italic = { family = "JetBrains Mono", style = "Italic"}

[mouse]
bindings = [
{ mouse = "Right", action = "Copy" }, 
{ mouse = "Right", mods = "Shift", action = "Paste"}
]

# Modified theme from https://github.com/projekt0n/github-theme-contrib
[colors.primary]
background = "#0a0c10"
foreground = "#f0f3f6"

[colors.cursor]
text = "#0a0c10"
cursor = "#f0f3f6"

[colors.normal]
black ="#7a828e"
red = "#ff9492"
green = "#87d75f"
yellow = "#f0b72f"
blue = "#5fd7ff"
magenta = "#cb9eff"
cyan = "#39c5cf"
white = "#d9dee3"

[colors.bright]
black = "#b1b5bc"
red = "#fff8f8"
green = "#c4ebb0"
yellow = "#f6d78e"
blue = "#c4f0ff"
magenta = "#ffffff"
cyan = "#8bdde2"
white = "#ffffff"

